language: python

python:
  - "3.6"

install:
  - python -m pip install numpy scipy pytest
  - make

os:
  - linux
  - osx

dist:
  - bionic

osx_image: xcode10

branches:
  only:
    - master

script: PYCI_NUM_THREADS=2 python -m pytest pyci
