package:
  name: "pyci"
  version: "0.3.5"

source:
  path: ../../

build:
  number: 0
  script:
    - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"
    - python setup.py build_ext -I {{ PREFIX }}/include
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

about:
  home: https://github.com/msricher/pyci
  description: A flexible ab-initio quantum chemistry library for Configuration Interaction
  license: GNU Version 3
  license_file: LICENSE

extra:
  recipe-maintainers: Michael Richer <richerm@mcmaster.ca>
