# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyCI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies and make C++ library
      run: |
        sudo apt-get install make git gcc python3 python3-dev python3-numpy python3-scipy python3-pytest python3-pycodestyle python3-pydocstyle
        make
    - name: Run PyCI tests
      run: |
        make test
