# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyCI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies and make C++ library
      run: |
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user numpy scipy pytest pycodestyle pydocstyle
        make
    - name: Run PyCI tests
      run: |
        make test
